name: Deploy Portfolio to IPFS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Pinata
        uses: PinataCloud/pinata-github-action@main
        with:
          pinata-jwt: ${{ secrets.PINATA_JWT }}
          path-to-deploy: './' 
          pinata-metadata: '{"name": "Portfolio Eduardo MM"}'
